# Generated by Django 3.2.25 on 2026-06-23 16:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_contactinfo_contactperson'),
    ]

    operations = [
        migrations.CreateModel(
            name='Diary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('average_score', models.DecimalField(decimal_places=2, max_digits=4, verbose_name='Средний балл')),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='diary', to='app.student', verbose_name='Студент')),
            ],
            options={
                'verbose_name': 'Школьный дневник',
                'verbose_name_plural': 'Школьные дневники',
            },
        ),
    ]
