# Generated by Django 3.2.25 on 2026-06-23 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_diary'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hobbies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=None, max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='person',
            name='hobbies',
            field=models.ManyToManyField(related_name='persons', to='app.Hobbies'),
        ),
    ]
