# Generated by Django 3.2.25 on 2026-06-23 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20260623_1650'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название')),
                ('pages', models.PositiveIntegerField(verbose_name='Количество страниц')),
                ('students', models.ManyToManyField(blank=True, related_name='books', to='app.Student', verbose_name='Студенты')),
            ],
            options={
                'verbose_name': 'Книга',
                'verbose_name_plural': 'Книги',
            },
        ),
    ]
