# Generated by Django 3.2.25 on 2026-06-23 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(default=None, max_length=255)),
                ('lastname', models.CharField(default=None, max_length=255)),
                ('age', models.IntegerField()),
                ('text', models.CharField(default=None, max_length=255)),
            ],
        ),
    ]
